### ISSUE TITLE
roff output contains <var>…</var> if \< and \> are used in Markdown

### ISSUE THREAD

**Issue by xtaran** [apjanke/ronn-ng#48]
Hi,

### Backgorund

Github didn't render the following synopsis as wanted:

```
`pxzgrep` [`-p`<n>] [`-V`] [<xzgrep options>] <pattern> <file1> <file2> [<more files>]
```

It was rendered by Github to

```
pxzgrep [-p] [-V] [] []
```

Which is actually correct as it parsed the words in angle brackets as HTML tags.

ronn though parsed it as wanted and rendered the parts in angle brackets in green (probably italics elsewhere):

```
pxzgrep [-pn] [-V] [xzgrep options] pattern file1 file2 [more files]
```

So I changed it to use escaped angle brackets as common in Markdown:

```
`pxzgrep` [`-p`\<n\>] [`-V`] [\<xzgrep options\>] \<pattern\> \<file1\> \<file2\> [\<more files\>]
```

Now Github shows it as wanted:

```
pxzgrep [-p<n>] [-V] [<xzgrep options>] <pattern> <file1> <file2> [<more files>]
```

### Issue

But instead the output in the ronn-generated man page now looks like this:

```
pxzgrep  [-p<var>n</var>]  [-V] [<var>xzgrep options</var>] <var>pattern</var> <var>file1</var <var>file2</var> [<var>more files</var>]
```

It looks like HTML syntax inside roff which is surely not what's wanted.

### Version

ronn version 0.9.1 as packaged in Debian Unstable in package version 0.9.1-1.

**Comment by apjanke** [comment]
Honestly, I have no idea what the Right Thing to do here is. Angle brackets are a common, legit thing to use in man pages for exactly the case you're using them for, but they're also HTML tags which are legit things to use inside HTML, which is legit inside Markdown.

**Comment by apjanke** [comment]
Well, clearly the behavior you're describing is the Wrong Thing, but I'm not sure what the correct solution is.

**Comment by apjanke** [comment]
Okay. So, personally I like the use of backslash to escape angle brackets like you're doing on GitHub. Doing a little research says that [regular Markdown does not support backslash-escaping angle brackets](https://daringfireball.net/projects/markdown/syntax#backslash) but [GitHub-Flavored Markdown does](https://daringfireball.net/projects/markdown/syntax#backslash), which is probably why it Just Works in GitHub for you.

Personally, I'm a fan of GitHub-Flavored Markdown because it's a more thorough spec than original Markdown, and has some nice extensions.

So maybe, ronn could do one of:
1. Add backslash-escaping specifically for angle brackets
2. Adopt GitHub-Flavored Markdown as its official flavor of Markdown
3. Add the ability to specify different flavors of Markdown using an option, and make GitHub-Flavored Markdown one of the supported options

I'm not a fan of 1. since it means deviating from spec and default Markdown library behavior. I could see either 2. or 3. being good choices. Given how common literal angle-brackets are in man pages, I'd think this escaping of angle brackets is enough on its own to justify supporting GHFM in some way.

**Comment by apjanke** [comment]
I've picked option 2: "Adopt GitHub-Flavored Markdown as our official flavor of Markdown", and the change has made it in to `master`, to go out in the upcoming 0.10.0 release.

I've added a test for the escaped angle bracket syntax in https://github.com/apjanke/ronn-ng/commit/6b265fd53082461ec3463166728fcd6bd5bc55ba, and it looks like it's working to me.

Closing as fixed. Please give it a try at your convenience, and if you're still having problems with escaping angle-brackets, re-open.
